const INITIAL_DATA = 'INITIAL_DATA'
const INITIAL_DATA_SUCCESS = 'INITIAL_DATA_SUCCESS'
const INITIAL_DATA_FAILURE = 'INITIAL_DATA_FAILURE'

const TIMER_START = 'TIMER_START'
const TIMER_GO_ON = 'TIMER_GO_ON'
const TIMER_TICK = 'TIMER_TICK'
const TIMER_PAUSE = 'TIMER_PAUSE'
const TIMER_STOP = 'TIMER_STOP'

module.exports = {
  INITIAL_DATA,
  TIMER_START,
  TIMER_GO_ON,
  TIMER_TICK,
  TIMER_PAUSE,
  TIMER_STOP,
}
