const INITIAL_DATA = 'INITIAL_DATA'

const TIMER_START = 'TIMER_START'
const TIMER_GO_ON = 'TIMER_GO_ON'
const TIMER_PAUSE = 'TIMER_PAUSE'
const TIMER_STOP = 'TIMER_STOP'

module.exports = {
  INITIAL_DATA,
  TIMER_START,
  TIMER_GO_ON,
  TIMER_PAUSE,
  TIMER_STOP,
}
