const ONE_SECOND = 1000
const ONE_MINUTE = ONE_SECOND * 60
const FIVE_MINUTES = ONE_MINUTE * 5
const FIFTEEN_MINUTES = ONE_MINUTE * 15
const TWENTY_FIVE_MINUTES = ONE_MINUTE * 25

module.exports = {
  ONE_SECOND,
  ONE_MINUTE,
  FIVE_MINUTES,
  FIFTEEN_MINUTES,
  TWENTY_FIVE_MINUTES,
}
